AWSTemplateFormatVersion: '2010-09-09'
Description: DynamoDB table for Habit Tracker
Resources:
  HabitTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: HabitTracker
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: user_idx
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
          Projection:
            ProjectionType: ALL
      BillingMode: PAY_PER_REQUEST
